import scrapy

class Offer(scrapy.Item):
	url = scrapy.Field()
	offer_name = scrapy.Field()
	company = scrapy.Field()
	company_size = scrapy.Field()
	job_locationsalary_1 = scrapy.Field()
	salary_1 = scrapy.Field()
	salary_1_description = scrapy.Field()
	salary_2 = scrapy.Field()
	salary_2_description = scrapy.Field()
	seniority_1 = scrapy.Field()
	seniority_2 = scrapy.Field()
	job_description = scrapy.Field()
	# Must_have = scrapy.Field()
	# Nice_to_have = scrapy.Field()

	# # work_methodology
	# Integration_tests = scrapy.Field()
	# Unit_tests = scrapy.Field()
	# Tester = scrapy.Field()
	# Agile_management = scrapy.Field()
	# Issue_tracking_tool = scrapy.Field()
	# Knowledge_repository = scrapy.Field()
	# Code_reviews = scrapy.Field()
	# Static_code_analysis = scrapy.Field()
	# Version_control_system = scrapy.Field()
	# Build_server = scrapy.Field()
	# QA_manager = scrapy.Field()
	# Distributed_team = scrapy.Field()
	# Research_and_Experimentation = scrapy.Field()
	# Pair_programming = scrapy.Field()
	# Workshops = scrapy.Field()
	# e2e_tests = scrapy.Field()
	# Commit_on_the_first_day = scrapy.Field()
	# One_command_build_possible = scrapy.Field()
	# Up_and_running_within_2h = scrapy.Field()
	# High_level_and_low_level_designs = scrapy.Field()
	# Feature_development_and_porting = scrapy.Field()
	# Regression_testing = scrapy.Field()
	# UAT_testing = scrapy.Field()
	# Agile_Testing = scrapy.Field()
	# Manual_tests = scrapy.Field()
	# Database = scrapy.Field()
	# Virtualization = scrapy.Field()
	# Cloud_infrastructure = scrapy.Field()
	# Operating_system = scrapy.Field()
	# Databases = scrapy.Field()
	# Network_virtualization = scrapy.Field()
	# Provisioning = scrapy.Field()
	# Networking_hardware = scrapy.Field()
	# Security = scrapy.Field()
	# Application_stack = scrapy.Field()
	# Operating_systems = scrapy.Field()

	# # equipment_supplied
	# Operating_System = scrapy.Field()
	# Computer = scrapy.Field()
	# Monitors = scrapy.Field()

	# # specs_category
	# Job_profile = scrapy.Field()
	# Start = scrapy.Field()
	# Contract_duration = scrapy.Field()
	# Paid_holiday = scrapy.Field()
	# Part_time_work = scrapy.Field()
	# Remote_possible = scrapy.Field()
	# Flexible_hours = scrapy.Field()
	# Travel_involved = scrapy.Field()
	# Freedom_to_choose_tools = scrapy.Field()
	# Relocation_package = scrapy.Field()
	# Remote_work = scrapy.Field()
	# Open-minded_developers_in_team = scrapy.Field()
	# Work_with_international_client = scrapy.Field()

	# Perks_in_the_office = scrapy.Field()
	# Benefits = scrapy.Field()


