integration_tests = scrapy.Field()


job_profile = scrapy.Field()
start = scrapy.Field()
contract_duration = scrapy.Field()
paid_holiday = scrapy.Field()
part_time_work = scrapy.Field()
remote_possible = scrapy.Field()
flexible_hours = scrapy.Field()
travel_involved = scrapy.Field()
freedom_to_choose_tools = scrapy.Field()
relocation_package = scrapy.Field()
remote_work = scrapy.Field()
open_minded_developers_in_team = scrapy.Field()
work_with_international_client = scrapy.Field()
