

job_profile_xpath = f'//nfj-posting-specs//div[re:test(text(), ".{specs_category[0]}.")]//parent::*//div[2]//text()'
start_xpath = f'//nfj-posting-specs//div[re:test(text(), ".{specs_category[0]}.")]//parent::*//div[2]//text()'
contract_duration_xpath = f'//nfj-posting-specs//div[re:test(text(), ".{specs_category[0]}.")]//parent::*//div[2]//text()'
paid_holiday_xpath = f'//nfj-posting-specs//div[re:test(text(), ".{specs_category[0]}.")]//parent::*//div[2]//text()'
part_time_work_xpath = f'//nfj-posting-specs//div[re:test(text(), ".{specs_category[0]}.")]//parent::*//div[2]//text()'
remote_possible_xpath = f'//nfj-posting-specs//div[re:test(text(), ".{specs_category[0]}.")]//parent::*//div[2]//text()'
flexible_hours_xpath = f'//nfj-posting-specs//div[re:test(text(), ".{specs_category[0]}.")]//parent::*//div[2]//text()'
travel_involved_xpath = f'//nfj-posting-specs//div[re:test(text(), ".{specs_category[0]}.")]//parent::*//div[2]//text()'
freedom_to_choose_tools_xpath = f'//nfj-posting-specs//div[re:test(text(), ".{specs_category[0]}.")]//parent::*//div[2]//text()'
relocation_package_xpath = f'//nfj-posting-specs//div[re:test(text(), ".{specs_category[0]}.")]//parent::*//div[2]//text()'
remote_work_xpath = f'//nfj-posting-specs//div[re:test(text(), ".{specs_category[0]}.")]//parent::*//div[2]//text()'
open_minded_developers_in_team_xpath = f'//nfj-posting-specs//div[re:test(text(), ".{specs_category[0]}.")]//parent::*//div[2]//text()'
work_with_international_client_xpath = f'//nfj-posting-specs//div[re:test(text(), ".{specs_category[0]}.")]//parent::*//div[2]//text()'
